name: Packager for WoWInterface and Wago. CurseForge packager is used natively.

on:
  push:
    branches: [main]
    tags: ["*"]

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package WoWInterface and Wago
        uses: BigWigsMods/packager@v2
        with:
          args: -L -n "{package-name}-{project-version}:{package-name}-{project-version}"
